name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the version of Python you want

      # Step 3: Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run Linter (flake8)
      - name: Run Linter (flake8)
        run: |
          pip install flake8
          flake8 your_app/ tests/

      # Step 6: Run Code Formatter as a Check (Black)
      - name: Check Code Formatting (Black)
        run: |
          pip install black
          black --check your_app/ tests/

      # Optional: Format code using autopep8
      # - name: Run Code Formatter (autopep8)
      #   run: |
      #     pip install autopep8
      #     autopep8 --in-place --recursive your_app/ tests/

      # Step 7: Run Unit Tests with Coverage
      - name: Run Tests with Coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=your_app tests/
