name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: creyD/action_autopep8@v3.1
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          
      - name: Install dependencies with Poetry
        run: |
          poetry install
          
      - name: Check and Install Streamlit if Missing
        run: |
          if ! poetry show streamlit; then
            poetry add streamlit
          fi
          
      - name: Verify Secret Access
        run: echo "Secret is set"
        env:
          AZURE_INFERENCE_CREDENTIAL: ${{ secrets.AZURE_INFERENCE_CREDENTIAL }}
        
      # - name: Test with pytest
      #   env:
      #     PYTHONPATH: ./project
      #   run: |
      #     export AZURE_INFERENCE_CREDENTIAL=${{ secrets.AZURE_INFERENCE_CREDENTIAL }}
      #     poetry run pytest --cov=project
        
      - name: Run SWE-Bench Dataset Tests
        env:
          HF_HOME: /tmp/transformers_cache  # Optional caching for Hugging Face datasets
          PYTHONPATH: ./project 
        run: |
          poetry run python tests/test.py
